readr/app/__init__.py
import flask

from werkzeug import utils

from readr.app import db
from readr.app.routes import main, books


def create_app(app_env=None):
    app = flask.Flask(__name__, template_folder="templates")

    load_config(app)
    db.init_app(app)
    register_routes(app)
    return app


def load_config(app):
    config_class = "readr.app.config." + app.env.capitalize()
    config = utils.import_string(config_class)()
    app.config.from_object(config)


def register_routes(app):
    app.register_blueprint(main.bp)
    app.register_blueprint(books.bp)

readr/app/routes/books.py
import flask

from readr.app import db
from readr.entities import book

bp = flask.Blueprint("books", __name__, url_prefix="/books")


@bp.route("/", methods=["GET"])
def list_books():
    books = _get_books(db.get_db())
    return flask.render_template("books/index.html", books=books)


def _get_books(db):
    books = db.query(book.Book).all()
    return books

readr/app/routes/main.py
import flask

bp = flask.Blueprint("main", __name__, url_prefix="/")


@bp.route("/", methods=["GET"])
def greet():
    return flask.render_template("index.html")

readr/app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Readr</title>
<nav>
    <h1>Readr</h1>
    <ul>
        <li><a href="{{ url_for('books.list_books') }}">Books<a>
    </ul>
</nav>
<section class="content">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% block content %}
    {% endblock %}
</section>

readr/app/templates/books/index.html
{% extends 'base.html' %}

{% block header %}
    <h1>
        {% block title %}Book Listing{% endblock %}
    </h1>
{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Title</th>
            <th>ISBN-10</th>
            <th>ISBN-13</th>
        </tr>
        {% for book in books %}
            <tr>
                <td>{{ book["title"] }}</td>
                <td>{{ book["isbn10"] }}</td>
                <td>{{ book["isbn13"] }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

readr/app/templates/index.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Welcome to Readr!{% endblock %}</h1>
{% endblock %}